apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: talha-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: registrykurs1.azurecr.io/frontend-app:talha-dev
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10